using Chaite.Core;
using System;
using System.Collections.Generic;
using System.Globalization;
using System.IO;
using System.Web.Script.Serialization;

namespace Chaite.Tests
{
    /// <summary>
    /// The C# observation builder against the trainer's own Python.
    ///
    /// <c>ChaiteObservation</c> claims to reproduce
    /// <c>training/chaite_env.py::obs_vector</c> feature for feature. That claim
    /// is the whole contract between training and the plugin: a silently
    /// different feature order, divisor or clip bound makes every shipped
    /// policy act on garbage, and no fight outcome would say which of the two
    /// sides was wrong. So it is checked against data the Python produced, not
    /// against a restatement of the C# code.
    ///
    /// The fixture is generated by
    /// <c>tests/Chaite.Tests/generate-observation-conformance-fixture.py</c>
    /// from real recorded bridge rows: the raw row and the float vector
    /// <c>obs_vector</c> returned for it. The test reads the configuration back
    /// out of the fixture's header line and constructs the builder to match, so
    /// the two sides can never disagree about which vector is being compared.
    ///
    /// What the fixture cannot cover is the NPC-threat block: every recorded
    /// stream in <c>artifacts/</c> predates the probe's nt2/nt4/nt8/nr* keys, so
    /// those twelve features are at the trainer's defaults in all 200 rows and a
    /// builder that dropped the whole block would still match. That block is
    /// pinned separately, against expectations produced by the repository's own
    /// Python, in <c>ChaiteObservationTranscribesTheNpcThreatBlock</c>.
    /// </summary>
    internal static partial class Program
    {
        private static void RunChaiteObservationConformanceRegressions()
        {
            Run(nameof(ChaiteObservationMatchesThePythonFixture),
                ChaiteObservationMatchesThePythonFixture);
            Run(nameof(ChaiteObservationSelectsTheRecordedProjectileWindow),
                ChaiteObservationSelectsTheRecordedProjectileWindow);
            Run(nameof(ChaiteObservationWindowAndAggregatesChangeTheWidth),
                ChaiteObservationWindowAndAggregatesChangeTheWidth);
            Run(nameof(ChaiteObservationReadsTheSessionConfiguration),
                ChaiteObservationReadsTheSessionConfiguration);
            Run(nameof(ChaiteObservationSeparatesTheTwoClipBounds),
                ChaiteObservationSeparatesTheTwoClipBounds);
            Run(nameof(ChaiteObservationTranscribesTheNpcThreatBlock),
                ChaiteObservationTranscribesTheNpcThreatBlock);
            Run(nameof(ChaiteObservationTranscribesTheBossAttackClock),
                ChaiteObservationTranscribesTheBossAttackClock);
            Run(nameof(ChaiteObservationTranscribesTheJumpCharges),
                ChaiteObservationTranscribesTheJumpCharges);
            Run(nameof(ExportedPolicyDriverRefusesAMismatchedWindow),
                ExportedPolicyDriverRefusesAMismatchedWindow);
        }

        /// <summary>
        /// The width agreement check the exported driver performs at startup:
        /// the loaded policy and the configured observation builder have to
        /// read and produce the same number of values, and the mismatch has to
        /// be reported when the driver is built rather than on the first tick.
        ///
        /// This is the reachable half of the driver from the offline suite --
        /// everything else needs a live game to read state from -- and it pins
        /// the failure that would otherwise be silent: a checkpoint trained on
        /// a 48-slot window driven by a plugin still configured for 12.
        ///
        /// The committed export is now two appended blocks narrower than the
        /// builder (the 12-value NPC-threat block and the 2-value Boss attack
        /// clock), so the refusal it pins is no longer hypothetical: until the
        /// policy is retrained on the wider observation and re-exported, the
        /// exported-policy path refuses to start rather than scoring 121 values
        /// with a first layer that reads 98.
        /// </summary>
        private static void ExportedPolicyDriverRefusesAMismatchedWindow()
        {
            var policy = ExportedPolicy.Load(PolicyBinaryPath());
            Equal(ExportedPolicy.ObservationCount, policy.ObservationDimension);

            // The committed export is the 98-input MLP trained before either
            // appended block existed, and no checkpoint trained on the wider
            // observation exists yet, so the builder's own default
            // configuration is now itself the mismatch this method exists to
            // catch: the driver has to refuse the checkpoint rather than feed
            // 121 values to a first layer that reads 98.
            var stale = Failure<InvalidOperationException>(() =>
                new ChaiteObservation(12, false, 4f).RequireObservationCount(
                    policy.ObservationDimension, policy.SourcePath));
            True(stale.Message.Contains(ChaiteObservation.SlotsVariable),
                "the width mismatch must name " +
                ChaiteObservation.SlotsVariable + ", not only the numbers: " +
                stale.Message);
            True(stale.Message.Contains("121"),
                "the width mismatch must report the builder's width: " +
                stale.Message);
            True(stale.Message.Contains("98"),
                "the width mismatch must report the policy's width: " +
                stale.Message);

            // The world bound changes the values but not the width, so it must
            // never be what makes two configurations disagree about the vector.
            Equal(new ChaiteObservation(12, false, 4f).ObservationCount,
                new ChaiteObservation(12, false, 12f).ObservationCount);

            // A wider window, or aggregates the checkpoint never saw, is the
            // other configuration error this exists to catch.
            var wide = Failure<InvalidOperationException>(() =>
                new ChaiteObservation(48, false, 4f).RequireObservationCount(
                    policy.ObservationDimension, policy.SourcePath));
            True(wide.Message.Contains(ChaiteObservation.SlotsVariable),
                "the width mismatch must name " +
                ChaiteObservation.SlotsVariable + ", not only the numbers: " +
                wide.Message);
            True(wide.Message.Contains("337"),
                "the width mismatch must report the builder's width: " +
                wide.Message);
            var aggregated = Failure<InvalidOperationException>(() =>
                new ChaiteObservation(12, true, 4f).RequireObservationCount(
                    policy.ObservationDimension, policy.SourcePath));
            True(aggregated.Message.Contains(
                ChaiteObservation.AggregatesVariable),
                "the width mismatch must name " +
                ChaiteObservation.AggregatesVariable + ": " +
                aggregated.Message);

            // The driver is inert unless the exported format is selected, which
            // is what keeps every existing configuration on the planner. The
            // loader owns that switch; this only asserts the two agree.
            var savedFormat = Environment.GetEnvironmentVariable(
                ExportedPolicy.FormatVariable);
            var savedFile = Environment.GetEnvironmentVariable(
                ExportedPolicy.FileVariable);
            try
            {
                Environment.SetEnvironmentVariable(
                    ExportedPolicy.FormatVariable, null);
                False(ExportedPolicy.IsExportedFormatSelected);
                True(ExportedPolicy.ForConfiguredFile() == null,
                    "the exported loader claimed a policy without " +
                    "CHAITE_POLICY_FORMAT=exported");
                Environment.SetEnvironmentVariable(
                    ExportedPolicy.FormatVariable,
                    ExportedPolicy.ExportedFormatName);
                Environment.SetEnvironmentVariable(
                    ExportedPolicy.FileVariable, PolicyBinaryPath());
                True(ExportedPolicy.IsExportedFormatSelected);
                True(ExportedPolicy.ForConfiguredFile() != null,
                    "the exported loader did not load the configured file");
            }
            finally
            {
                Environment.SetEnvironmentVariable(
                    ExportedPolicy.FormatVariable, savedFormat);
                Environment.SetEnvironmentVariable(
                    ExportedPolicy.FileVariable, savedFile);
                ExportedPolicy.ResetCache();
            }
        }

        private const string ObservationFixtureSchema =
            "chaite-observation-conformance/v1";

        private static string ObservationFixturePath()
        {
            return Path.Combine(FindRepositoryRoot(), "tests", "Chaite.Tests",
                "fixtures", "observation-conformance.jsonl");
        }

        /// <summary>
        /// Every fixture row: the C# builder's vector must equal the Python
        /// vector, entry for entry, to within 1e-5.
        ///
        /// A mismatch reports the first differing index, the feature's name,
        /// and both values, because "vector 137 differs" is not actionable on
        /// its own and the whole point of the test is to localise a drift.
        /// </summary>
        private static void ChaiteObservationMatchesThePythonFixture()
        {
            var path = ObservationFixturePath();
            True(File.Exists(path), "the observation conformance fixture is " +
                "missing: " + path + "; regenerate it with tests/Chaite.Tests/" +
                "generate-observation-conformance-fixture.py");

            var parser = new JavaScriptSerializer { MaxJsonLength = int.MaxValue };
            var lines = File.ReadAllLines(path);
            True(lines.Length >= 2, "the fixture holds no rows: " + path);

            var header = (Dictionary<string, object>)parser.DeserializeObject(
                lines[0]);
            Equal(ObservationFixtureSchema, Convert.ToString(
                header["schema"], CultureInfo.InvariantCulture));
            var slots = Convert.ToInt32(header["projectile_slots"],
                CultureInfo.InvariantCulture);
            var aggregates = Convert.ToBoolean(header["aggregates"],
                CultureInfo.InvariantCulture);
            var worldBound = Convert.ToSingle(header["world_bound"],
                CultureInfo.InvariantCulture);
            var declaredDim = Convert.ToInt32(header["obs_dim"],
                CultureInfo.InvariantCulture);
            var declaredRows = Convert.ToInt32(header["row_count"],
                CultureInfo.InvariantCulture);

            var observation = new ChaiteObservation(slots, aggregates,
                worldBound);
            Equal(declaredDim, observation.ObservationCount);
            // The committed export is the 98-input MLP trained before the
            // NPC-threat block existed, so it is now exactly one NPC block
            // narrower than the builder's default. That is not a licence to
            // relax the check: the twelve new features are appended after the
            // values that checkpoint was trained on, which keeps its 98 indices
            // meaning what they meant, and this assertion is what would catch a
            // block inserted in the middle instead. The shipped policy still has
            // to be retrained and re-exported before the driver accepts it --
            // ExportedPolicyDriverRefusesAMismatchedWindow pins that refusal.
            Equal(ExportedPolicy.ObservationCount +
                ChaiteObservation.NpcThreatFeatureCount +
                ChaiteObservation.BossClockFeatureCount +
                ChaiteObservation.JumpChargeFeatureCount,
                observation.ObservationCount);

            var names = observation.FeatureNames();
            var values = new float[observation.ObservationCount];
            var rows = 0;
            var maximumDifference = 0f;
            var maximumDifferenceIndex = -1;
            var maximumDifferenceRow = -1;
            var maximumDifferenceObserved = 0f;
            var maximumDifferenceExpected = 0f;
            var nonZeroProjectileRows = 0;
            var npcThreatRows = 0;
            var bossClockRows = 0;
            var jumpChargeRows = 0;
            var collapsedRows = 0;
            for (var line = 1; line < lines.Length; line++)
            {
                if (lines[line].Length == 0) continue;
                var entry = (Dictionary<string, object>)parser.DeserializeObject(
                    lines[line]);
                var raw = (Dictionary<string, object>)entry["raw"];
                var expectedValues = (object[])entry["obs"];
                Equal(observation.ObservationCount, expectedValues.Length);

                // Coverage counters, asserted after the loop. A fixture whose
                // NPC block and Boss clock are all defaults compares equal on
                // both sides for a reason that has nothing to do with either
                // block being transcribed correctly, and that is exactly how
                // this test passed vacuously while every recorded stream
                // predated the keys: 200 rows, zero of them carrying a bubble.
                if (raw.ContainsKey("nt4") &&
                    Convert.ToSingle(raw["nt4"], CultureInfo.InvariantCulture) > 0f)
                    npcThreatRows++;
                if (raw.ContainsKey("bs3") &&
                    Convert.ToSingle(raw["bs3"], CultureInfo.InvariantCulture) >= 0f)
                    bossClockRows++;
                // Any charge flag being set is the presence test. The fixture
                // gives the balloons exactly one type, so in practice this
                // counts jc0; a builder that dropped the block would leave it
                // at zero on every row.
                foreach (var chargeKey in new[] { "jc0", "jc1", "jc2", "jc3",
                    "jc4", "jc5", "jc6", "jc7", "jc8" })
                    if (raw.ContainsKey(chargeKey) &&
                        Convert.ToSingle(raw[chargeKey],
                            CultureInfo.InvariantCulture) != 0f)
                    {
                        jumpChargeRows++;
                        break;
                    }
                if (raw.ContainsKey("pe") &&
                    Convert.ToSingle(raw["pe"], CultureInfo.InvariantCulture) > 0f)
                    collapsedRows++;

                observation.Fill(ObservationRowFromBridgeRow(raw), values);
                var rowHasProjectiles = false;
                for (var index = 0; index < values.Length; index++)
                {
                    var expected = Convert.ToSingle(expectedValues[index],
                        CultureInfo.InvariantCulture);
                    var difference = Math.Abs(values[index] - expected);
                    if (difference > maximumDifference)
                    {
                        maximumDifference = difference;
                        maximumDifferenceIndex = index;
                        maximumDifferenceRow = rows;
                        // Captured now, not read back from the buffer at the
                        // end: the buffer holds the LAST row by then, so a
                        // failure message that re-read it would report a value
                        // from a different row than the one it names.
                        maximumDifferenceObserved = values[index];
                        maximumDifferenceExpected = expected;
                    }
                    if (index >= ChaiteObservation.BaseFeatureCount &&
                        index < values.Length -
                            ChaiteObservation.TailFeatureCount -
                            ChaiteObservation.NpcThreatFeatureCount -
                            ChaiteObservation.BossClockFeatureCount -
                            ChaiteObservation.JumpChargeFeatureCount -
                            (aggregates
                                ? ChaiteObservation.AggregateFeatureCount : 0) &&
                        expected != 0f)
                        rowHasProjectiles = true;
                }
                if (rowHasProjectiles) nonZeroProjectileRows++;
                rows++;
            }

            Equal(declaredRows, rows);
            True(rows >= 200, "the fixture carries " + rows + " rows, not the " +
                "200 real observations the contract requires");
            // A fixture whose projectile block is all zeroes would not notice a
            // builder that never wrote one, so the sample has to prove it
            // exercises the window.
            True(nonZeroProjectileRows > 0, "the fixture exercises no " +
                "projectile slot at all, so a builder that dropped the whole " +
                "window would pass it");
            // The same argument for the two appended blocks. Without these the
            // test is green on a fixture that never saw a bubble or a live Boss
            // clock, which is precisely the state it was in until the fixture
            // was regenerated from a stream that carries the keys.
            True(npcThreatRows > 0, "the fixture carries no row with a live NPC " +
                "threat (nt4 > 0), so a builder that dropped the whole " +
                ChaiteObservation.NpcThreatFeatureCount + "-value NPC block " +
                "would still pass: regenerate it from a stream recorded after " +
                "the probe started writing nt2/nt4/nt8/nr*");
            True(bossClockRows > 0, "the fixture carries no row with a live Boss " +
                "attack clock (bs3 >= 0), so a builder that dropped the whole " +
                ChaiteObservation.BossClockFeatureCount + "-value Boss-clock " +
                "block would still pass: regenerate it from a stream recorded " +
                "after the probe started writing bs2/bs3");
            True(jumpChargeRows > 0, "the fixture carries no row with a multi-jump " +
                "charge available, so a builder that dropped the whole " +
                ChaiteObservation.JumpChargeFeatureCount + "-value jump-charge " +
                "block would still pass: regenerate it from a stream recorded " +
                "after the probe started writing jc0..jc8");

            const float tolerance = 1e-5f;
            True(maximumDifference <= tolerance, "row " + maximumDifferenceRow +
                " differs at index " + maximumDifferenceIndex + " (" +
                names[maximumDifferenceIndex] + "): the C# builder produced " +
                maximumDifferenceObserved.ToString("R",
                    CultureInfo.InvariantCulture) + " but Python produced " +
                maximumDifferenceExpected.ToString("R",
                    CultureInfo.InvariantCulture) + " (|difference| = " +
                maximumDifference.ToString("R", CultureInfo.InvariantCulture) +
                ")");

            Console.WriteLine("observation conformance: " + rows + " real rows" +
                " from " + DescribeFixtureSources(header) + ", max |C# - " +
                "Python| = " + maximumDifference.ToString("R",
                    CultureInfo.InvariantCulture) + ", " +
                nonZeroProjectileRows + " rows with a non-empty projectile " +
                "window, " + npcThreatRows + " with a live NPC threat, " +
                bossClockRows + " with a live Boss clock, " + jumpChargeRows +
                " with a multi-jump charge, " + collapsedRows +
                " with a collapsed projectile type");
        }

        private static string DescribeFixtureSources(
            Dictionary<string, object> header)
        {
            object sources;
            if (!header.TryGetValue("sources", out sources)) return "an " +
                "unrecorded source";
            var values = sources as object[];
            if (values == null) return "an unrecorded source";
            var parts = new List<string>();
            foreach (var value in values) parts.Add(Convert.ToString(value,
                CultureInfo.InvariantCulture));
            return string.Join(", ", parts.ToArray());
        }

        /// <summary>
        /// The projectile window the builder selects must be the one the probe
        /// recorded.
        ///
        /// The fixture's own <c>pr</c> arrays are the probe's answer, so
        /// re-deriving the window from the full candidate list is only possible
        /// for the entries that fit in it. What is checked here is the part
        /// that can be: the recorded order must be the order the builder's
        /// selection key produces, which is what makes the live path's window
        /// the trained one rather than a permutation of it.
        /// </summary>
        private static void ChaiteObservationSelectsTheRecordedProjectileWindow()
        {
            var path = ObservationFixturePath();
            True(File.Exists(path), "the observation conformance fixture is " +
                "missing: " + path);
            var parser = new JavaScriptSerializer { MaxJsonLength = int.MaxValue };
            var lines = File.ReadAllLines(path);
            var header = (Dictionary<string, object>)parser.DeserializeObject(
                lines[0]);
            var slots = Convert.ToInt32(header["projectile_slots"],
                CultureInfo.InvariantCulture);
            var observation = new ChaiteObservation(slots, false,
                Convert.ToSingle(header["world_bound"],
                    CultureInfo.InvariantCulture));

            var outOfOrder = 0;
            var multiSlotRows = 0;
            var candidates = new List<ChaiteProjectileObservation>();
            for (var line = 1; line < lines.Length; line++)
            {
                if (lines[line].Length == 0) continue;
                var entry = (Dictionary<string, object>)parser.DeserializeObject(
                    lines[line]);
                var raw = (Dictionary<string, object>)entry["raw"];
                var recorded = ProjectilesFromBridgeRow(raw);
                if (recorded == null || recorded.Length < 2) continue;
                multiSlotRows++;
                candidates.Clear();
                for (var index = 0; index < recorded.Length; index++)
                    candidates.Add(recorded[index]);
                var row = ObservationRowFromBridgeRow(raw);
                observation.SelectProjectiles(candidates, row, PlayerWidth,
                    PlayerHeight, observation.ProjectileBuffer);
                for (var index = 0; index + 1 < recorded.Length; index++)
                {
                    if (!SameProjectile(observation.ProjectileBuffer[index],
                            recorded[index]))
                    {
                        outOfOrder++;
                        break;
                    }
                }
            }
            True(multiSlotRows > 0, "no fixture row carries more than one " +
                "projectile, so the window selection is untested");
            Equal(0, outOfOrder);
            Console.WriteLine("projectile window: " + multiSlotRows + " rows " +
                "with a multi-entry window, all in the recorded order");
        }

        private const float PlayerWidth = 20f;
        private const float PlayerHeight = 42f;

        private static bool SameProjectile(ChaiteProjectileObservation left,
            ChaiteProjectileObservation right)
        {
            return left.X == right.X && left.Y == right.Y &&
                left.VelocityX == right.VelocityX &&
                left.VelocityY == right.VelocityY &&
                left.Width == right.Width && left.Height == right.Height &&
                left.Type == right.Type;
        }

        /// <summary>
        /// The window and the aggregate flag change the vector's width, and the
        /// four widths the trainer can produce are the four the builder
        /// produces.
        ///
        /// The two widths grew by four on 2026-09-21: the 12-value NPC-threat
        /// block and the 2-value Boss attack clock. They are appended, never
        /// inserted, so every earlier value keeps its index and the old widths
        /// stay exact prefixes of the new ones.
        /// </summary>
        private static void ChaiteObservationWindowAndAggregatesChangeTheWidth()
        {
            Equal(121, new ChaiteObservation(12, false, 4f).ObservationCount);
            Equal(125, new ChaiteObservation(12, true, 4f).ObservationCount);
            Equal(337, new ChaiteObservation(48, false, 4f).ObservationCount);
            Equal(341, new ChaiteObservation(48, true, 4f).ObservationCount);
            // The feature names are the layout written down a second time, so
            // they have to cover every slot of every configuration; a name list
            // that ran short would misreport the index a drift was found at.
            Equal(121, new ChaiteObservation(12, false, 4f).FeatureNames().Length);
            Equal(125, new ChaiteObservation(12, true, 4f).FeatureNames().Length);
            Equal(341, new ChaiteObservation(48, true, 4f).FeatureNames().Length);

            // A padded slot is six literal zeroes, not a zero-valued
            // projectile: the trainer's loop writes [0.0] * 6 past the end of
            // the list. A builder that instead formatted a default projectile
            // would emit -px/1000 and -py/1000, a phantom threat at the world
            // origin, on every tick whose hostile count is below the window --
            // which is most of them. The player sits at y 2000 here precisely
            // so that mistake would show up as -2 rather than as zero.
            var observation = new ChaiteObservation(4, false, 4f);
            var row = new ChaiteObservationRow
            {
                PlayerX = 1000f, PlayerY = 2000f,
                Projectiles = new[]
                {
                    new ChaiteProjectileObservation
                    {
                        X = 1100f, Y = 2000f, Width = 8f, Height = 8f,
                        Type = 42f
                    }
                }
            };
            var values = observation.ObsVector(row);
            Equal(ChaiteObservation.BaseFeatureCount + 6 * 4 +
                ChaiteObservation.TailFeatureCount +
                ChaiteObservation.NpcThreatFeatureCount +
                ChaiteObservation.BossClockFeatureCount +
                ChaiteObservation.JumpChargeFeatureCount, values.Length);
            // The one real slot is present, scaled by the trainer's divisors.
            Equal(.1f, values[ChaiteObservation.BaseFeatureCount]);
            Equal(0f, values[ChaiteObservation.BaseFeatureCount + 1]);
            Near(42f / 1000f, values[ChaiteObservation.BaseFeatureCount + 5]);
            for (var slot = 1; slot < 4; slot++)
                for (var feature = 0; feature < 6; feature++)
                    Equal(0f, values[ChaiteObservation.BaseFeatureCount +
                        slot * 6 + feature]);

            // The aggregates are appended at the very end, after the tail, and
            // the tail is unchanged by them.
            var aggregated = new ChaiteObservation(4, true, 4f);
            var aggregateRow = new ChaiteObservationRow
            {
                PlayerX = 1000f, PlayerY = 2000f,
                ProjectileCount = 64f, ProjectilesWithin200 = 8f,
                ProjectilesWithin400 = 16f, ProjectilesWithin800 = 32f
            };
            var aggregateValues = aggregated.ObsVector(aggregateRow);
            Equal(ChaiteObservation.BaseFeatureCount + 6 * 4 +
                ChaiteObservation.TailFeatureCount +
                ChaiteObservation.NpcThreatFeatureCount +
                ChaiteObservation.BossClockFeatureCount +
                ChaiteObservation.JumpChargeFeatureCount +
                ChaiteObservation.AggregateFeatureCount,
                aggregateValues.Length);
            var tail = aggregateValues.Length -
                ChaiteObservation.AggregateFeatureCount;
            for (var index = ChaiteObservation.BaseFeatureCount + 6 * 4;
                index < tail; index++)
                Equal(values[index], aggregateValues[index]);
            Equal(1f, aggregateValues[tail]);
            Equal(1f, aggregateValues[tail + 1]);
            Equal(1f, aggregateValues[tail + 2]);
            Equal(1f, aggregateValues[tail + 3]);
        }

        /// <summary>
        /// The environment variables the training session uses are the ones the
        /// builder reads, with the trainer's own defaults when they are unset.
        /// </summary>
        private static void ChaiteObservationReadsTheSessionConfiguration()
        {
            var savedSlots = Environment.GetEnvironmentVariable(
                ChaiteObservation.SlotsVariable);
            var savedAggregates = Environment.GetEnvironmentVariable(
                ChaiteObservation.AggregatesVariable);
            var savedBound = Environment.GetEnvironmentVariable(
                ChaiteObservation.WorldBoundVariable);
            try
            {
                Environment.SetEnvironmentVariable(
                    ChaiteObservation.SlotsVariable, null);
                Environment.SetEnvironmentVariable(
                    ChaiteObservation.AggregatesVariable, null);
                Environment.SetEnvironmentVariable(
                    ChaiteObservation.WorldBoundVariable, null);
                var defaults = ChaiteObservation.FromEnvironment();
                Equal(ChaiteObservation.DefaultProjectileSlots,
                    defaults.ProjectileSlots);
                False(defaults.Aggregates);
                Equal(ChaiteObservation.DefaultWorldBound, defaults.WorldBound);
                // 22 base + 12 slots x 6 + 4 tail + 12 NPC threats + 2 Boss
                // clock, no aggregates: the trainer's own default OBS_DIM. It is
                // no longer the width of the committed export, which predates
                // both appended blocks.
                Equal(121, defaults.ObservationCount);

                Environment.SetEnvironmentVariable(
                    ChaiteObservation.SlotsVariable, "48");
                Environment.SetEnvironmentVariable(
                    ChaiteObservation.AggregatesVariable, "on");
                Environment.SetEnvironmentVariable(
                    ChaiteObservation.WorldBoundVariable, "12");
                var configured = ChaiteObservation.FromEnvironment();
                Equal(48, configured.ProjectileSlots);
                True(configured.Aggregates);
                Equal(12f, configured.WorldBound);
                Equal(341, configured.ObservationCount);

                // A zero window is clamped up to one, as the trainer clamps it;
                // a malformed bound is refused rather than guessed.
                Environment.SetEnvironmentVariable(
                    ChaiteObservation.SlotsVariable, "0");
                Equal(1, ChaiteObservation.FromEnvironment().ProjectileSlots);
                Environment.SetEnvironmentVariable(
                    ChaiteObservation.WorldBoundVariable, "not-a-number");
                Throws<InvalidOperationException>(() =>
                    ChaiteObservation.FromEnvironment());
            }
            finally
            {
                Environment.SetEnvironmentVariable(
                    ChaiteObservation.SlotsVariable, savedSlots);
                Environment.SetEnvironmentVariable(
                    ChaiteObservation.AggregatesVariable, savedAggregates);
                Environment.SetEnvironmentVariable(
                    ChaiteObservation.WorldBoundVariable, savedBound);
            }
        }

        /// <summary>
        /// The two clip bounds are different functions with different limits,
        /// and collapsing them is the single easiest way to ship a policy that
        /// sees a different state than it trained on. The world bound is
        /// raised by a session that needed the whole arena, and it must move
        /// the world features without moving anything else.
        /// </summary>
        private static void ChaiteObservationSeparatesTheTwoClipBounds()
        {
            var row = new ChaiteObservationRow
            {
                // The measured arena runs to px 10922, so 10.922 is inside a
                // 12.0 world bound and far outside the fixed 4.0 clip.
                PlayerX = 10922f, PlayerY = 11791f,
                PlayerVelocityX = 160f, PlayerVelocityY = -160f,
                WingTime = 600f, DashDelay = 300f, EocDash = 150f,
                JumpTicks = 200f, ElapsedTicks = 6000f,
                BossAi0 = 150f, BossAi1 = 80f
            };
            var tight = new ChaiteObservation(12, false, 4f);
            var wide = new ChaiteObservation(12, false, 12f);
            var tightValues = tight.ObsVector(row);
            var wideValues = wide.ObsVector(row);

            // World features move with the bound.
            Equal(4f, tightValues[0]);
            Near(10.922f, wideValues[0]);
            Equal(4f, tightValues[1]);
            Near(11.791f, wideValues[1]);
            // Everything clipped by the fixed 4.0 does not.
            for (var index = 2; index < ChaiteObservation.BaseFeatureCount;
                index++)
            {
                if (index == 10 || index == 11 || index == 14 || index == 15 ||
                    index == 16)
                    continue;
                Equal(tightValues[index], wideValues[index]);
            }
            // The boss-relative world features move too, and the separation is
            // scaled by 1500 before the world clip, not by 1000. The sign is
            // the player minus the boss, so it is checked in both directions:
            // a builder that emitted a distance where the trainer emits a
            // displacement would be invisible at the symmetric magnitudes.
            var separationRow = new ChaiteObservationRow
            {
                PlayerX = 10000f, PlayerY = 0f, BossX = 0f, BossY = 0f
            };
            Equal(4f, tight.ObsVector(separationRow)[14]);
            Near(10f, wide.ObsVector(separationRow)[14]);
            Equal(4f, tight.ObsVector(separationRow)[16]);
            Near(10000f / 1500f, wide.ObsVector(separationRow)[16]);
            var negativeSeparation = new ChaiteObservationRow
            {
                PlayerX = 0f, PlayerY = 0f, BossX = 10000f, BossY = 0f
            };
            Equal(-4f, tight.ObsVector(negativeSeparation)[14]);
            Near(-10f, wide.ObsVector(negativeSeparation)[14]);
            // The distance itself is unsigned and identical either way.
            Near(10000f / 1500f, wide.ObsVector(negativeSeparation)[16]);
        }

        /// <summary>
        /// The NPC-threat block: the twelve features appended after the tail for
        /// the threats the projectile window cannot contain, because Fishron's
        /// Detonating Bubbles (NPC 371), the Sharknado-generating bubbles
        /// (372/373) and the Sharknado column (384) are NPCs rather than
        /// projectiles.
        ///
        /// The frozen conformance fixture cannot pin these: it replays real
        /// recorded bridge rows, and every stream in artifacts/ predates the
        /// probe's nt2/nt4/nt8/nr* keys, so all 200 of its rows carry the
        /// trainer's defaults and a builder that dropped or reordered this whole
        /// block would still match. The expectations below therefore come from
        /// running the repository's own <c>obs_vector</c> on the same synthetic
        /// rows, not from a restatement of the C# code:
        ///
        /// <code>
        /// obs_vector(row without the keys)[12..24] ==
        ///     [0,0,0,0,0,0,0,0,-0.002,0,0,0]
        /// obs_vector(nt2 8, nt4 4, nt8 16, nrx 1000, nry -2000, nrvx 16,
        ///            nrvy -32, nrt 384, nrl 1000, nrw 64, nrh 32)[12..24] ==
        ///     [1, .5, 1, 1, -2, 1, -2, 1.4907119, .768, 1, 1, 1]
        /// obs_vector(nt2 3, nt4 .5, nt8 40, nrx -4000, nry 100, nrvx -100,
        ///            nrvy 8, nrt -1)[12..24] ==
        ///     [.375, .0625, 2.5, -4, .1, -4, .5, 2.6674998, -.002, 0, 0, 0]
        /// </code>
        ///
        /// The third row is the load-bearing one. It saturates both fixed-clip
        /// paths (a -4000 px offset and a -100 velocity both stop at -4),
        /// exercises the 1500-scaled distance, and pins the trainer's
        /// <c>int(nt4) &gt; 0</c> test: a fractional count is "no threat" there
        /// while the count feature itself keeps its fractional value.
        /// </summary>
        private static void ChaiteObservationTranscribesTheNpcThreatBlock()
        {
            var observation = new ChaiteObservation(12, false, 4f);
            var start = ChaiteObservation.BaseFeatureCount +
                12 * ChaiteObservation.ProjectileFeatureCount +
                ChaiteObservation.TailFeatureCount;
            // The block is 12 wide and the Boss clock and the jump charges
            // follow it, so the remaining width past the block's start is the
            // block plus the clock plus the charges.
            Equal(ChaiteObservation.NpcThreatFeatureCount +
                ChaiteObservation.BossClockFeatureCount +
                ChaiteObservation.JumpChargeFeatureCount,
                observation.ObservationCount - start);

            // The probe's "nothing there" row: zero geometry, zero counts and
            // the type at -1, which is the trainer's own default for a missing
            // nrt. The type is a small negative feature rather than a flag of
            // its own, and the row has to set it: the struct's default of zero
            // is NPC 0, a real type.
            var absent = observation.ObsVector(new ChaiteObservationRow
            {
                NpcThreatType = -1f
            });
            for (var index = 0; index < ChaiteObservation.NpcThreatFeatureCount;
                index++)
            {
                if (index == 8) continue;
                Equal(0f, absent[start + index]);
            }
            Near(-0.002f, absent[start + 8]);

            var full = new ChaiteObservationRow
            {
                NpcThreatsWithin200 = 8f, NpcThreatsWithin400 = 4f,
                NpcThreatsWithin800 = 16f, NpcThreatRelativeX = 1000f,
                NpcThreatRelativeY = -2000f, NpcThreatVelocityX = 16f,
                NpcThreatVelocityY = -32f, NpcThreatType = 384f,
                NpcThreatLife = 1000f, NpcThreatWidth = 64f,
                NpcThreatHeight = 32f
            };
            var fullValues = observation.ObsVector(full);
            Near(1f, fullValues[start]);
            Near(.5f, fullValues[start + 1]);
            Near(1f, fullValues[start + 2]);
            Near(1f, fullValues[start + 3]);
            Near(-2f, fullValues[start + 4]);
            Near(1f, fullValues[start + 5]);
            Near(-2f, fullValues[start + 6]);
            Near(1.4907119274139404f, fullValues[start + 7]);
            Near(.7680000066757202f, fullValues[start + 8]);
            Near(1f, fullValues[start + 9]);
            Near(1f, fullValues[start + 10]);
            Near(1f, fullValues[start + 11]);

            var partial = new ChaiteObservationRow
            {
                NpcThreatsWithin200 = 3f, NpcThreatsWithin400 = .5f,
                NpcThreatsWithin800 = 40f, NpcThreatRelativeX = -4000f,
                NpcThreatRelativeY = 100f, NpcThreatVelocityX = -100f,
                NpcThreatVelocityY = 8f, NpcThreatType = -1f
            };
            var partialValues = observation.ObsVector(partial);
            Near(.375f, partialValues[start]);
            Near(.0625f, partialValues[start + 1]);
            Near(2.5f, partialValues[start + 2]);
            Near(-4f, partialValues[start + 3]);
            Near(.10000000149011612f, partialValues[start + 4]);
            Near(-4f, partialValues[start + 5]);
            Near(.5f, partialValues[start + 6]);
            Near(2.6674997806549072f, partialValues[start + 7]);
            Near(-.0020000000949949026f, partialValues[start + 8]);
            Equal(0f, partialValues[start + 9]);
            Equal(0f, partialValues[start + 10]);
            Equal(0f, partialValues[start + 11]);
        }

        /// <summary>
        /// The Boss attack clock: the two features appended after the NPC-threat
        /// block for the Boss's native timer and sequence.
        ///
        /// These are the fields the reviewed formula scripts branch on, not a
        /// refinement of <c>bs</c>/<c>bi</c>. For Duke Fishron,
        /// <c>FormulaScriptController.TryReadInput</c> reads <c>ai[0]</c> as the
        /// state, <c>ai[2]</c> as the timer and <c>ai[3]</c> as the sequence, and
        /// <c>FishronFormulaStateContract.TimerLimit</c> turns (state, sequence,
        /// difficulty, enraged) into the tick the state ends on.
        ///
        /// The load-bearing property is the <c>-1</c> sentinel. The probe writes
        /// <c>-1</c> for "no Boss alive" -- the same value it writes for
        /// <c>bs</c> -- so the trainer's <c>(value + 1) / divisor</c> scaling has
        /// to put "absent" at exactly zero. Dividing the raw value instead would
        /// map the sentinel onto the same zero a genuinely-zero timer produces,
        /// and "there is no Boss" and "the attack just started" call for
        /// opposite behaviour. The expectations come from running the
        /// repository's own <c>obs_vector</c> on the same synthetic rows:
        ///
        /// <code>
        /// obs_vector(bs2 -1, bs3 -1)[112..114] == [0, 0]
        /// obs_vector(bs2  0, bs3  0)[112..114] == [0.00552486, 0.0625]
        /// obs_vector(bs2 180, bs3 11)[112..114] == [1, 0.75]
        /// obs_vector(bs2  30, bs3  2)[112..114] == [0.17127071, 0.1875]
        /// </code>
        ///
        /// The second row is the one that would pass under the wrong scaling, so
        /// the test asserts the absent row and the zero row differ.
        /// </summary>
        private static void ChaiteObservationTranscribesTheBossAttackClock()
        {
            var observation = new ChaiteObservation(12, false, 4f);
            var start = ChaiteObservation.BaseFeatureCount +
                12 * ChaiteObservation.ProjectileFeatureCount +
                ChaiteObservation.TailFeatureCount +
                ChaiteObservation.NpcThreatFeatureCount;
            Equal(ChaiteObservation.BossClockFeatureCount +
                ChaiteObservation.JumpChargeFeatureCount,
                observation.ObservationCount - start);

            // The probe's "no Boss" row.
            var absent = observation.ObsVector(new ChaiteObservationRow
            {
                BossAi2 = -1f, BossAi3 = -1f
            });
            Equal(0f, absent[start]);
            Equal(0f, absent[start + 1]);

            // A Boss whose timer and sequence are genuinely zero. Under the
            // wrong (unshifted) scaling this row and the absent row would be
            // identical.
            var zero = observation.ObsVector(new ChaiteObservationRow
            {
                BossAi2 = 0f, BossAi3 = 0f
            });
            Near(1f / 181f, zero[start]);
            Near(1f / 16f, zero[start + 1]);
            True(zero[start] != absent[start],
                "a Boss at timer 0 must not read the same as no Boss at all");

            // The top of Fishron's range: 180 ticks inside one state and
            // sequence 11, the largest the state contract admits.
            var full = observation.ObsVector(new ChaiteObservationRow
            {
                BossAi2 = 180f, BossAi3 = 11f
            });
            Near(1f, full[start]);
            Near(.75f, full[start + 1]);

            // A mid-state timer and a mid-sequence attack, so the
            // non-saturating part of both ranges is pinned too. The +1 offsets
            // are the "a real zero must not read as absent" shift and are
            // independent of which Boss fills the clock.
            var midState = observation.ObsVector(new ChaiteObservationRow
            {
                BossAi2 = 30f, BossAi3 = 2f
            });
            Near(31f / 181f, midState[start]);
            Near(3f / 16f, midState[start + 1]);

            // The block is appended after the NPC block, so the 110 values an
            // earlier checkpoint was trained on keep their indices.
            var both = observation.ObsVector(new ChaiteObservationRow
            {
                NpcThreatType = 384f, BossAi2 = 180f, BossAi3 = 11f
            });
            Near(384f / 500f, both[start - 4]);
        }

        /// <summary>
        /// The multi-jump charges must reach the observation, and the order of
        /// the nine flags must be the one both sides claim.
        ///
        /// The order is the whole risk here. A reordering on either side would
        /// still produce a self-consistent vector, so nothing else in the suite
        /// would notice; only pinning the mapping from a named charge to its own
        /// index does.
        /// </summary>
        private static void ChaiteObservationTranscribesTheJumpCharges()
        {
            var observation = new ChaiteObservation(12, false, 4f);
            var start = ChaiteObservation.BaseFeatureCount +
                12 * ChaiteObservation.ProjectileFeatureCount +
                ChaiteObservation.TailFeatureCount +
                ChaiteObservation.NpcThreatFeatureCount +
                ChaiteObservation.BossClockFeatureCount;
            Equal(ChaiteObservation.JumpChargeFeatureCount,
                observation.ObservationCount - start);

            // No charges at all: every flag zero.
            var none = observation.ObsVector(new ChaiteObservationRow
            {
                JumpCharges = new float[ChaiteObservation.JumpChargeFeatureCount]
            });
            for (var index = 0; index < ChaiteObservation.JumpChargeFeatureCount;
                index++)
                Equal(0f, none[start + index]);

            // Exactly one charge, walked across every index, so a transposition
            // of any two positions fails rather than cancelling out.
            for (var held = 0; held < ChaiteObservation.JumpChargeFeatureCount;
                held++)
            {
                var charges = new float[ChaiteObservation.JumpChargeFeatureCount];
                charges[held] = 1f;
                var vector = observation.ObsVector(new ChaiteObservationRow
                {
                    JumpCharges = charges
                });
                for (var index = 0;
                    index < ChaiteObservation.JumpChargeFeatureCount; index++)
                    Near(index == held ? .25f : 0f, vector[start + index]);
            }

            // The loadout that motivated the block: the Bundle of Balloons.
            // MEASURED on a recorded lilith-wolf stream (254,957 rows, all of
            // them with the balloons equipped): jc0, jc1 and jc2 are true on
            // every single row while jc3..jc8 are false on every row. So the
            // bundle grants THREE charges -- cloud, sandstorm and blizzard --
            // not the one a single-sum design would have reported. That is the
            // concrete argument for nine flags over one count: a sum would read
            // 3 and leave the policy unable to tell which jump it would spend.
            var balloons = observation.ObsVector(new ChaiteObservationRow
            {
                JumpCharges = new[] { 1f, 1f, 1f, 0f, 0f, 0f, 0f, 0f, 0f }
            });
            Near(.25f, balloons[start]);
            Near(.25f, balloons[start + 1]);
            Near(.25f, balloons[start + 2]);
            Near(0f, balloons[start + 3]);
            True(balloons[start] != none[start],
                "a player holding a cloud jump must not read the same as one " +
                "with no charges left");
            True(balloons[start + 2] != balloons[start + 3],
                "the bundle's third charge must be distinguishable from a type " +
                "the bundle does not grant");

            // A short or absent array must not throw and must not shift the
            // block: the row mapper is fed recorded streams that predate the
            // keys, so a null JumpCharges is a real input.
            var absent = observation.ObsVector(new ChaiteObservationRow());
            for (var index = 0; index < ChaiteObservation.JumpChargeFeatureCount;
                index++)
                Equal(0f, absent[start + index]);

            // The names are part of the contract, in the same order.
            var names = observation.FeatureNames();
            for (var index = 0; index < ChaiteObservation.JumpChargeFeatureCount;
                index++)
                Equal("jump_charge_" + ChaiteObservation.JumpChargeNames[index],
                    names[start + index]);
        }

        /// <summary>
        /// The exception a failing call threw, so a test can assert on the
        /// message. The suite's own <c>Throws&lt;T&gt;</c> discards it, and the
        /// message is the whole point of a configuration error.
        /// </summary>
        private static TException Failure<TException>(Action action)
            where TException : Exception
        {
            try
            {
                action();
            }
            catch (TException thrown)
            {
                return thrown;
            }
            throw new InvalidOperationException("expected " +
                typeof(TException).Name + " but the call returned normally");
        }

        private static void Near(float expected, float actual)
        {
            if (Math.Abs(expected - actual) > 1e-5f)
                throw new InvalidOperationException("expected " +
                    expected.ToString("R", CultureInfo.InvariantCulture) +
                    ", got " + actual.ToString("R",
                        CultureInfo.InvariantCulture));
        }

        /// <summary>
        /// Turns one recorded bridge row into the builder's input, reading
        /// exactly the keys the trainer reads and applying the same fallbacks.
        /// This is the fixture half of the conformance test; the live half is
        /// <c>TerrariaFacade.BuildChaiteObservationRow</c>, which reads the
        /// same quantities out of the game.
        /// </summary>
        private static ChaiteObservationRow ObservationRowFromBridgeRow(
            Dictionary<string, object> raw)
        {
            var row = new ChaiteObservationRow
            {
                PlayerX = RowNumber(raw, "px"),
                PlayerY = RowNumber(raw, "py"),
                PlayerVelocityX = RowNumber(raw, "vx"),
                PlayerVelocityY = RowNumber(raw, "vy"),
                PlayerLife = RowNumber(raw, "pl"),
                PlayerLifeMax = RowNumber(raw, "plm"),
                WingTime = RowNumber(raw, "wt"),
                WingTimeMax = RowNumber(raw, "wm"),
                DashDelay = RowNumber(raw, "dd"),
                EocDash = RowNumber(raw, "eo"),
                JumpTicks = RowNumber(raw, "jt"),
                Dead = RowFlag(raw, "dead"),
                BossX = RowNumber(raw, "bx"),
                BossY = RowNumber(raw, "by"),
                BossVelocityX = RowNumber(raw, "bvx"),
                BossVelocityY = RowNumber(raw, "bvy"),
                BossLife = RowNumber(raw, "bl"),
                BossLifeMax = RowNumber(raw, "blm"),
                BossAi0 = raw.ContainsKey("bs") ? RowNumber(raw, "bs") : -1f,
                BossAi1 = RowNumber(raw, "bi"),
                ElapsedTicks = RowNumber(raw, "et"),
                Hits = RowNumber(raw, "hits"),
                Projectiles = ProjectilesFromBridgeRow(raw),
                // The NPC-threat keys are newer than the recorded streams: a row
                // that predates them reads as the trainer's own defaults, which
                // is zero geometry and a -1 type.
                NpcThreatsWithin200 = RowNumber(raw, "nt2"),
                NpcThreatsWithin400 = RowNumber(raw, "nt4"),
                NpcThreatsWithin800 = RowNumber(raw, "nt8"),
                NpcThreatRelativeX = RowNumber(raw, "nrx"),
                NpcThreatRelativeY = RowNumber(raw, "nry"),
                NpcThreatVelocityX = RowNumber(raw, "nrvx"),
                NpcThreatVelocityY = RowNumber(raw, "nrvy"),
                NpcThreatType = raw.ContainsKey("nrt") ? RowNumber(raw, "nrt") : -1f,
                NpcThreatLife = RowNumber(raw, "nrl"),
                NpcThreatWidth = RowNumber(raw, "nrw"),
                NpcThreatHeight = RowNumber(raw, "nrh"),
                // The Boss-clock keys are newer still. A row that predates them
                // reads as the trainer's own default for a missing bs2/bs3,
                // which is the -1 sentinel, not zero.
                BossAi2 = raw.ContainsKey("bs2") ? RowNumber(raw, "bs2") : -1f,
                BossAi3 = raw.ContainsKey("bs3") ? RowNumber(raw, "bs3") : -1f,
                // The jump-charge keys are the newest. A row that predates them
                // has no charges, which is the honest default: the recorded
                // streams before this key existed were flown on loadouts whose
                // balloons the fixture never granted anyway.
                JumpCharges = JumpChargesFromBridgeRow(raw)
            };
            if (raw.ContainsKey("pc"))
            {
                row.ProjectileCount = RowNumber(raw, "pc");
                row.ProjectilesWithin200 = RowNumber(raw, "p2");
                row.ProjectilesWithin400 = RowNumber(raw, "p4");
                row.ProjectilesWithin800 = RowNumber(raw, "p8");
            }
            return row;
        }

        /// <summary>Reads the multi-jump charge flags, one per balloon type, in
        /// the assembly's own field order. The order is the contract: a
        /// reordering on either side would silently swap two charges, and both
        /// sides would still look self-consistent, so the names are pinned in
        /// <see cref="ChaiteObservation.JumpChargeNames"/> and asserted in
        /// <c>ChaiteObservationTranscribesTheJumpCharges</c>.</summary>
        private static float[] JumpChargesFromBridgeRow(
            Dictionary<string, object> raw)
        {
            string[] keys = { "jc0", "jc1", "jc2", "jc3", "jc4", "jc5", "jc6",
                "jc7", "jc8" };
            Equal(ChaiteObservation.JumpChargeFeatureCount, keys.Length);
            var charges = new float[keys.Length];
            for (var index = 0; index < keys.Length; index++)
                charges[index] = RowFlag(raw, keys[index]) ? 1f : 0f;
            return charges;
        }

        private static ChaiteProjectileObservation[] ProjectilesFromBridgeRow(
            Dictionary<string, object> raw)
        {
            object declared;
            if (!raw.TryGetValue("pr", out declared)) return null;
            var entries = declared as object[];
            if (entries == null) return null;
            var shots = new ChaiteProjectileObservation[entries.Length];
            for (var index = 0; index < entries.Length; index++)
            {
                var shot = (Dictionary<string, object>)entries[index];
                shots[index] = new ChaiteProjectileObservation
                {
                    X = RowNumber(shot, "x"),
                    Y = RowNumber(shot, "y"),
                    VelocityX = RowNumber(shot, "vx"),
                    VelocityY = RowNumber(shot, "vy"),
                    Width = RowNumber(shot, "w"),
                    Height = RowNumber(shot, "h"),
                    Type = RowNumber(shot, "ty")
                };
            }
            return shots;
        }

        private static float RowNumber(Dictionary<string, object> row, string key)
        {
            object value;
            if (!row.TryGetValue(key, out value) || value == null) return 0f;
            if (value is bool) return (bool)value ? 1f : 0f;
            return Convert.ToSingle(value, CultureInfo.InvariantCulture);
        }

        private static bool RowFlag(Dictionary<string, object> row, string key)
        {
            object value;
            if (!row.TryGetValue(key, out value) || value == null) return false;
            if (value is bool) return (bool)value;
            return Convert.ToSingle(value, CultureInfo.InvariantCulture) != 0f;
        }
    }
}
