using Chaite.Core;
using System;
using System.Collections.Generic;
using System.Globalization;
using System.IO;
using System.Web.Script.Serialization;

namespace Chaite.Tests
{
    /// <summary>
    /// The exported-policy loader: the 98-input / 12-action MLP that
    /// training/export_policy.py writes. The forward pass is pinned against
    /// vectors generated by the repository's own Python from the real bridge
    /// observation stream, so this is a cross-implementation check and not a
    /// restatement of the C# code.
    ///
    /// What is NOT covered: nothing here drives a fight. The loader is verified
    /// as a pure function of a weight file and an observation vector. Applying
    /// its action to the game is a separate, untested change.
    /// </summary>
    internal static partial class Program
    {
        private static void RunExportedPolicyRegressions()
        {
            Run(nameof(ExportedPolicyLoadsTheExportedFile),
                ExportedPolicyLoadsTheExportedFile);
            Run(nameof(ExportedPolicyMatchesThePythonReference),
                ExportedPolicyMatchesThePythonReference);
            Run(nameof(ExportedPolicyBreaksTiesByLowestIndex),
                ExportedPolicyBreaksTiesByLowestIndex);
            Run(nameof(ExportedPolicyDecodesTheActionAlphabet),
                ExportedPolicyDecodesTheActionAlphabet);
            Run(nameof(ExportedPolicyLoadsTheTrainedWidth),
                ExportedPolicyLoadsTheTrainedWidth);
            Run(nameof(ExportedPolicyRejectsMalformedFiles),
                ExportedPolicyRejectsMalformedFiles);
            Run(nameof(ExportedPolicySelectsTheNewFormatWithoutBreakingTheOldOne),
                ExportedPolicySelectsTheNewFormatWithoutBreakingTheOldOne);
        }

        /// <summary>The exported weights and manifest are checked in as test
        /// fixtures under tests/Chaite.Tests/fixtures, NOT read from artifacts/.
        /// artifacts/ is gitignored (it holds tens of gigabytes of probe runs),
        /// so a regression that read the export from there would pass on the
        /// machine that produced it and fail on every clean checkout and in CI.
        /// Refresh the fixtures with training/export_policy.py when the policy
        /// they pin is retrained.</summary>
        private static string PolicyExportDirectory()
        {
            return Path.Combine(FindRepositoryRoot(), "tests", "Chaite.Tests",
                "fixtures");
        }

        private static string PolicyBinaryPath()
        {
            return Path.Combine(PolicyExportDirectory(), "obsb1.bin");
        }

        private static string PolicyManifestPath()
        {
            return Path.Combine(PolicyExportDirectory(), "obsb1.json");
        }

        private static string PolicyReferenceVectorPath()
        {
            return Path.Combine(FindRepositoryRoot(), "tests", "Chaite.Tests",
                "policy-reference-vectors.json");
        }

        /// <summary>The real export parses, and its shapes are the ones the
        /// manifest records. Both halves matter: the loader's own idea of the
        /// layout and the manifest are written down independently, and a
        /// transposed or padded read would still produce a plausible action
        /// histogram.</summary>
        private static void ExportedPolicyLoadsTheExportedFile()
        {
            var path = PolicyBinaryPath();
            True(File.Exists(path),
                "the exported policy is missing: " + path + ". artifacts/ is " +
                "gitignored, so this regression only runs where the export " +
                "exists; regenerate it with training/export_policy.py.");

            var policy = ExportedPolicy.Load(path);
            Equal(path, policy.SourcePath);
            Equal(3, policy.LayerCount);
            Equal(ExportedPolicy.ObservationCount, policy.ObservationDimension);
            Equal(ExportedPolicy.ActionCount, policy.OutputCount);
            Equal("128x98, 128x128, 12x128", policy.LayerShapes);

            var rows = policy.LayerRows;
            var columns = policy.LayerColumns;
            Equal(3, rows.Length);
            Equal(3, columns.Length);
            Equal(128, rows[0]);
            Equal(98, columns[0]);
            Equal(128, rows[1]);
            Equal(128, columns[1]);
            Equal(12, rows[2]);
            Equal(128, columns[2]);

            var manifestPath = PolicyManifestPath();
            True(File.Exists(manifestPath),
                "the export manifest is missing: " + manifestPath);
            var manifest = (Dictionary<string, object>)new JavaScriptSerializer
            {
                MaxJsonLength = int.MaxValue
            }.DeserializeObject(File.ReadAllText(manifestPath));
            Equal(ExportedPolicy.ObservationCount, Convert.ToInt32(
                manifest["obs_dim"], CultureInfo.InvariantCulture));
            Equal(ExportedPolicy.ActionCount, Convert.ToInt32(
                manifest["action_count"], CultureInfo.InvariantCulture));
            var shapes = (object[])manifest["layer_shapes"];
            Equal(3, shapes.Length);
            for (var layer = 0; layer < shapes.Length; layer++)
            {
                var shape = (object[])shapes[layer];
                Equal(rows[layer], Convert.ToInt32(shape[0],
                    CultureInfo.InvariantCulture));
                Equal(columns[layer], Convert.ToInt32(shape[1],
                    CultureInfo.InvariantCulture));
            }

            // No observation normalisation, on either side. The exporter refuses
            // to write a file for a policy that normalises, and this loader must
            // never invent one: the manifest is the record of that promise.
            object normalisation;
            True(!manifest.TryGetValue("obs_normalize", out normalisation) ||
                normalisation == null,
                "the manifest asks for observation normalisation, which the " +
                "loader does not implement");
        }

        /// <summary>
        /// The loader's greedy action equals the exporter's numpy reference on
        /// real observations from the live bridge stream.
        ///
        /// The vectors were generated by
        /// tests/Chaite.Tests/generate-policy-reference-vectors.py: rows with
        /// <c>et &gt; 5</c> out of artifacts/bridge-obsb1/bridge.obs.jsonl,
        /// converted with training/chaite_env.py's own <c>obs_vector</c> under
        /// <c>CHAITE_OBS_WORLD_BOUND=12</c>, and labelled by
        /// training/export_policy.py's <c>reference_forward</c>. Nothing on the
        /// C# side chose the expected answers.
        /// </summary>
        private static void ExportedPolicyMatchesThePythonReference()
        {
            var vectorPath = PolicyReferenceVectorPath();
            True(File.Exists(vectorPath),
                "the reference vectors are missing: " + vectorPath + "; " +
                "regenerate them with tests/Chaite.Tests/" +
                "generate-policy-reference-vectors.py");
            var policy = ExportedPolicy.Load(PolicyBinaryPath());

            var parser = new JavaScriptSerializer
            {
                MaxJsonLength = int.MaxValue
            };
            var vectors = (object[])parser.DeserializeObject(
                File.ReadAllText(vectorPath));
            True(vectors.Length >= 200,
                "the fixture carries " + vectors.Length + " vectors, not the " +
                "200 real observations the contract requires");

            var observation = new float[ExportedPolicy.ObservationCount];
            var histogram = new Dictionary<int, int>();
            for (var index = 0; index < vectors.Length; index++)
            {
                var record = (Dictionary<string, object>)vectors[index];
                var values = (object[])record["obs"];
                Equal(ExportedPolicy.ObservationCount, values.Length);
                for (var i = 0; i < values.Length; i++)
                    observation[i] = Convert.ToSingle(values[i],
                        CultureInfo.InvariantCulture);
                var expected = Convert.ToInt32(record["action"],
                    CultureInfo.InvariantCulture);
                True(expected >= 0 && expected < ExportedPolicy.ActionCount,
                    "vector " + index + " carries an impossible action " +
                    expected);
                var actual = policy.ChooseAction(observation);
                True(actual == expected, "vector " + index + " expected action " +
                    expected + " but the loader chose " + actual);
                int count;
                histogram.TryGetValue(actual, out count);
                histogram[actual] = count + 1;
            }

            // A loader that returned a constant would agree with a fixture that
            // exercised one action, so the fixture has to prove it does not.
            True(histogram.Count > 1, "the fixture exercises " +
                histogram.Count + " distinct action(s); a constant-returning " +
                "stub would pass it");
            Console.WriteLine("policy reference vectors: " + vectors.Length +
                " real observations, " + histogram.Count +
                " distinct actions, histogram " + DescribeHistogram(histogram));
        }

        private static string DescribeHistogram(Dictionary<int, int> histogram)
        {
            var keys = new List<int>(histogram.Keys);
            keys.Sort();
            var parts = new List<string>();
            foreach (var key in keys) parts.Add(key + "=" + histogram[key]);
            return string.Join(", ", parts.ToArray());
        }

        /// <summary>Ties go to the lowest index, which is what the strict
        /// comparison in the argmax buys. The second half is the interesting
        /// one: an exact tie between two non-zero logits, where a &gt;= or a
        /// reversed scan would answer differently.</summary>
        private static void ExportedPolicyBreaksTiesByLowestIndex()
        {
            var observation = new float[ExportedPolicy.ObservationCount];
            var flat = ExportedPolicy.Parse(
                BuildPolicyBinary(CanonicalLayerShapes(), null), "flat");
            Equal(0, flat.ChooseAction(observation));
            var logits = new float[ExportedPolicy.ActionCount];
            flat.Forward(observation, logits);
            for (var i = 0; i < logits.Length; i++)
                Equal(0f, logits[i]);

            var tiedBias = new float[ExportedPolicy.ActionCount];
            tiedBias[5] = 1f;
            tiedBias[7] = 1f;
            var tied = ExportedPolicy.Parse(
                BuildPolicyBinary(CanonicalLayerShapes(), tiedBias), "tied");
            Equal(5, tied.ChooseAction(observation));
        }

        /// <summary>The action encoding, pinned to the literal alphabet the
        /// manifest documents rather than to the same arithmetic restated. A
        /// silently changed mapping would send the wrong key presses for every
        /// action while every forward-pass test still passed.</summary>
        private static void ExportedPolicyDecodesTheActionAlphabet()
        {
            var expected = new[]
            {
                "-1/0/0", "-1/0/1", "-1/1/0", "-1/1/1",
                "0/0/0", "0/0/1", "0/1/0", "0/1/1",
                "1/0/0", "1/0/1", "1/1/0", "1/1/1"
            };
            Equal(ExportedPolicy.ActionCount, expected.Length);
            for (var action = 0; action < ExportedPolicy.ActionCount; action++)
            {
                int direction;
                bool jump;
                bool dash;
                ExportedPolicy.DecodeAction(action, out direction, out jump,
                    out dash);
                Equal(expected[action], direction + "/" + (jump ? 1 : 0) + "/" +
                    (dash ? 1 : 0));
            }

            var outOfRange = 0;
            var anyJump = false;
            var anyDash = false;
            Throws<ArgumentOutOfRangeException>(() => ExportedPolicy.DecodeAction(
                -1, out outOfRange, out anyJump, out anyDash));
            Throws<ArgumentOutOfRangeException>(() => ExportedPolicy.DecodeAction(
                ExportedPolicy.ActionCount, out outOfRange, out anyJump,
                out anyDash));
        }

        /// <summary>Every malformed input fails closed. A corrupt header must
        /// never produce a garbage action, and it must never index past the
        /// arrays it describes, so each case here is an exception rather than a
        /// returned value.</summary>
        /// <summary>
        /// The width the bridge-trained policies actually use: 121 observations
        /// and 24 logits.
        ///
        /// MEASURED 2026-09-21: the loader enforced the legacy 98/12 as "the
        /// width this build produces" and refused this file outright, so the
        /// trained policy could not be shipped at all. This pins that it loads,
        /// reports its own width, and that the 24-action alphabet decodes the
        /// independent DOWN bit the 12-action one does not have.
        /// </summary>
        private static void ExportedPolicyLoadsTheTrainedWidth()
        {
            var policy = ExportedPolicy.Parse(BuildPolicyBinary(new[]
            {
                new[] { 128, 121 },
                new[] { 128, 128 },
                new[] { 24, 128 }
            }, null), "trained-width");

            Equal(121, policy.ObservationDimension);
            Equal(24, policy.OutputCount);
            Equal("128x121, 128x128, 24x128", policy.LayerShapes);

            // direction = action/8 - 1, up = (action%8)/4, down = (action%4)/2,
            // dash = action%2, over all 24, with every control reachable.
            var directions = new bool[3];
            var ups = new bool[2];
            var downs = new bool[2];
            var dashes = new bool[2];
            for (var action = 0; action < 24; action++)
            {
                int direction;
                bool up;
                bool down;
                bool dash;
                ExportedPolicy.DecodeAction(24, action, out direction, out up,
                    out down, out dash);
                Equal(action / 8 - 1, direction);
                Equal((action % 8) / 4 != 0, up);
                Equal((action % 4) / 2 != 0, down);
                Equal(action % 2 != 0, dash);
                directions[direction + 1] = true;
                ups[up ? 1 : 0] = true;
                downs[down ? 1 : 0] = true;
                dashes[dash ? 1 : 0] = true;
            }
            True(directions[0] && directions[1] && directions[2],
                "all three directions are reachable");
            True(ups[0] && ups[1], "up is reachable both ways");
            True(downs[0] && downs[1], "down is reachable both ways");
            True(dashes[0] && dashes[1], "dash is reachable both ways");

            // The two alphabets must NOT agree: the same integer means different
            // controls under each, which is why the width is an argument.
            int narrowDirection;
            bool narrowUp;
            bool narrowDown;
            bool narrowDash;
            ExportedPolicy.DecodeAction(12, 6, out narrowDirection, out narrowUp,
                out narrowDown, out narrowDash);
            Equal(0, narrowDirection);
            Equal(false, narrowDown);

            int wideDirection;
            bool wideUp;
            bool wideDown;
            bool wideDash;
            ExportedPolicy.DecodeAction(24, 6, out wideDirection, out wideUp,
                out wideDown, out wideDash);
            Equal(-1, wideDirection);
            Equal(true, wideDown);

            // An alphabet with no written-down encoding is refused, not guessed.
            Throws<ArgumentOutOfRangeException>(() =>
                ExportedPolicy.DecodeAction(16, 0, out wideDirection,
                    out wideUp, out wideDown, out wideDash));
        }

        private static void ExportedPolicyRejectsMalformedFiles()
        {
            var good = BuildPolicyBinary(CanonicalLayerShapes(), null);
            // The synthetic file is only evidence about the failure cases if it
            // is itself accepted.
            Equal(3, ExportedPolicy.Parse(good, "synthetic").LayerCount);

            var badMagic = (byte[])good.Clone();
            badMagic[0] = (byte)'X';
            Throws<InvalidDataException>(() =>
                ExportedPolicy.Parse(badMagic, "bad-magic"));
            Throws<InvalidDataException>(() =>
                ExportedPolicy.Parse(new byte[8], "short-magic"));
            Throws<InvalidDataException>(() =>
                ExportedPolicy.Parse(new byte[13], "truncated-version"));

            var badVersion = (byte[])good.Clone();
            badVersion[13] = 2;
            Throws<InvalidDataException>(() =>
                ExportedPolicy.Parse(badVersion, "bad-version"));

            var truncated = new byte[good.Length - 4];
            Array.Copy(good, truncated, truncated.Length);
            Throws<InvalidDataException>(() =>
                ExportedPolicy.Parse(truncated, "truncated"));
            Throws<InvalidDataException>(() =>
                ExportedPolicy.Parse(new byte[21], "no-layers"));

            Throws<InvalidDataException>(() => ExportedPolicy.Parse(
                BuildPolicyBinary(new int[0][], null), "zero-layers"));
            // The observation width is deliberately NOT Parse's decision any
            // more. This build emits whatever ChaiteObservation is configured
            // for, so Parse accepts any internally consistent width and the
            // mismatch is refused where the configured width actually lives:
            // ChaitePolicyDriver.RequireObservationCount, covered by
            // ExportedPolicyDriverRefusesAMismatchedWindow. MEASURED 2026-09-21:
            // enforcing the legacy 98 here made every bridge-trained 121-wide
            // checkpoint unloadable, so the trained policy could never ship.
            Equal(3, ExportedPolicy.Parse(
                BuildPolicyBinary(new[]
                {
                    new[] { 128, ExportedPolicy.ObservationCount - 1 },
                    new[] { 128, 128 },
                    new[] { ExportedPolicy.ActionCount, 128 }
                }, null), "narrower-observation").LayerCount);
            // The action count IS still Parse's decision, because a width with
            // no written-down encoding cannot be recovered from later.
            Throws<InvalidDataException>(() => ExportedPolicy.Parse(
                BuildPolicyBinary(new[]
                {
                    new[] { 128, ExportedPolicy.ObservationCount },
                    new[] { 128, 128 },
                    new[] { ExportedPolicy.ActionCount - 1, 128 }
                }, null), "wrong-action-count"));
            Throws<InvalidDataException>(() => ExportedPolicy.Parse(
                BuildPolicyBinary(new[]
                {
                    new[] { 128, ExportedPolicy.ObservationCount },
                    new[] { 128, 128 },
                    new[] { 16, 128 }
                }, null), "undecodable-action-count"));
            Throws<InvalidDataException>(() => ExportedPolicy.Parse(
                BuildPolicyBinary(new[]
                {
                    new[] { 128, ExportedPolicy.ObservationCount },
                    new[] { 128, 64 },
                    new[] { ExportedPolicy.ActionCount, 128 }
                }, null), "broken-chain"));
            Throws<InvalidDataException>(() => ExportedPolicy.Parse(
                BuildPolicyBinary(new[]
                {
                    new[] { 0, ExportedPolicy.ObservationCount }
                }, null), "zero-rows"));

            var trailing = new byte[good.Length + 4];
            Array.Copy(good, trailing, good.Length);
            Throws<InvalidDataException>(() =>
                ExportedPolicy.Parse(trailing, "trailing-bytes"));

            Throws<ArgumentNullException>(() =>
                ExportedPolicy.Parse(null, "null-bytes"));
            Throws<ArgumentException>(() => ExportedPolicy.Load(""));
            Throws<FileNotFoundException>(() => ExportedPolicy.Load(
                Path.Combine(Path.GetTempPath(),
                    "chaite-absent-policy-" + Guid.NewGuid().ToString("N") +
                    ".bin")));

            // Argument validation, so a caller's mistake cannot reach the
            // weight arrays either.
            var policy = ExportedPolicy.Parse(good, "synthetic");
            Throws<ArgumentNullException>(() => policy.ChooseAction(null));
            Throws<ArgumentException>(() =>
                policy.ChooseAction(new float[ExportedPolicy.ObservationCount - 1]));
            Throws<ArgumentNullException>(() => policy.Forward(
                new float[ExportedPolicy.ObservationCount], null));
            Throws<ArgumentException>(() => policy.Forward(
                new float[ExportedPolicy.ObservationCount],
                new float[ExportedPolicy.ActionCount - 1]));
        }

        /// <summary>
        /// The two formats share CHAITE_POLICY_FILE, so the selector is what
        /// keeps them from fighting over it. Three properties matter: with no
        /// selector the residual format behaves exactly as it always has; with
        /// the exported format selected the new loader owns the file; and the
        /// residual loader then stands down instead of failing closed on a
        /// binary it cannot parse, because the scripts call it on every tick.
        /// </summary>
        private static void ExportedPolicySelectsTheNewFormatWithoutBreakingTheOldOne()
        {
            var previousFormat = Environment.GetEnvironmentVariable(
                ExportedPolicy.FormatVariable);
            var previousFile = Environment.GetEnvironmentVariable(
                LearnedPolicy.FileVariable);
            var previousRoutes = Environment.GetEnvironmentVariable(
                LearnedPolicy.RoutesVariable);
            var residualPath = Path.Combine(Path.GetTempPath(),
                "chaite-format-select-residual-" +
                Guid.NewGuid().ToString("N") + ".txt");
            var route = FormulaRoute.FishronFairyWingsDash;
            try
            {
                // 1. No selector at all: the pre-existing configuration. The
                // exported loader must be inert and the residual must load.
                WriteTestPolicy(residualPath, -1, null);
                Environment.SetEnvironmentVariable(
                    ExportedPolicy.FormatVariable, null);
                Environment.SetEnvironmentVariable(
                    LearnedPolicy.FileVariable, residualPath);
                Environment.SetEnvironmentVariable(
                    LearnedPolicy.RoutesVariable, route.ToString());
                LearnedPolicy.ResetCache();
                ExportedPolicy.ResetCache();
                Equal(PolicyFileFormat.Residual, ExportedPolicy.ResolveFormat());
                False(ExportedPolicy.IsExportedFormatSelected);
                True(ExportedPolicy.ForConfiguredFile() == null,
                    "the exported loader must be inert while the residual " +
                    "format owns CHAITE_POLICY_FILE");
                True(LearnedPolicy.ForRoute(route) != null,
                    "the residual format stopped loading when the format " +
                    "variable was unset");

                // 2. Explicitly residual: identical to unset.
                Environment.SetEnvironmentVariable(
                    ExportedPolicy.FormatVariable,
                    ExportedPolicy.ResidualFormatName);
                Equal(PolicyFileFormat.Residual, ExportedPolicy.ResolveFormat());
                True(ExportedPolicy.ForConfiguredFile() == null);

                // 3. Exported selected: the new loader owns the file, and the
                // residual loader yields instead of parsing the binary.
                Environment.SetEnvironmentVariable(
                    ExportedPolicy.FormatVariable,
                    ExportedPolicy.ExportedFormatName);
                Environment.SetEnvironmentVariable(
                    LearnedPolicy.FileVariable, PolicyBinaryPath());
                Environment.SetEnvironmentVariable(
                    LearnedPolicy.RoutesVariable, null);
                LearnedPolicy.ResetCache();
                ExportedPolicy.ResetCache();
                True(ExportedPolicy.IsExportedFormatSelected);
                var policy = ExportedPolicy.ForConfiguredFile();
                True(policy != null, "the exported format was selected but no " +
                    "policy was loaded");
                Equal(3, policy.LayerCount);
                Equal(ExportedPolicy.ObservationCount,
                    policy.ObservationDimension);
                Equal(ExportedPolicy.ActionCount, policy.OutputCount);
                True(ReferenceEquals(policy, ExportedPolicy.ForConfiguredFile()),
                    "the policy must be loaded once per process");
                True(LearnedPolicy.ForRoute(route) == null,
                    "the residual loader must stand down while the exported " +
                    "format owns CHAITE_POLICY_FILE, not throw on a binary");

                // 4. A selector that names neither format is refused rather
                // than guessed.
                Environment.SetEnvironmentVariable(
                    ExportedPolicy.FormatVariable, "yolo");
                Throws<InvalidOperationException>(() =>
                    ExportedPolicy.ResolveFormat());

                // 5. Exported selected with no file at all.
                Environment.SetEnvironmentVariable(
                    ExportedPolicy.FormatVariable,
                    ExportedPolicy.ExportedFormatName);
                Environment.SetEnvironmentVariable(
                    LearnedPolicy.FileVariable, null);
                ExportedPolicy.ResetCache();
                Throws<InvalidOperationException>(() =>
                    ExportedPolicy.ForConfiguredFile());
            }
            finally
            {
                Environment.SetEnvironmentVariable(
                    ExportedPolicy.FormatVariable, previousFormat);
                Environment.SetEnvironmentVariable(
                    LearnedPolicy.FileVariable, previousFile);
                Environment.SetEnvironmentVariable(
                    LearnedPolicy.RoutesVariable, previousRoutes);
                LearnedPolicy.ResetCache();
                ExportedPolicy.ResetCache();
                if (File.Exists(residualPath)) File.Delete(residualPath);
            }
        }

        private static int[][] CanonicalLayerShapes()
        {
            return new[]
            {
                new[] { 128, ExportedPolicy.ObservationCount },
                new[] { 128, 128 },
                new[] { ExportedPolicy.ActionCount, 128 }
            };
        }

        /// <summary>
        /// A synthetic version-1 export, so the format's failure paths can be
        /// exercised without a fixture file on disk. All weights are zero and
        /// the biases come from <paramref name="lastBias"/>, which is enough to
        /// choose any logit pattern the tests need. The magic, the version and
        /// the layer framing are written here independently of the loader, so a
        /// loader that misread its own header would not agree with this.
        /// </summary>
        private static byte[] BuildPolicyBinary(int[][] shapes, float[] lastBias)
        {
            using (var stream = new MemoryStream())
            using (var writer = new BinaryWriter(stream))
            {
                writer.Write(new byte[]
                {
                    0x43, 0x48, 0x41, 0x49, 0x54, 0x45, 0x50,
                    0x4F, 0x4C, 0x49, 0x43, 0x59, 0x00
                });
                writer.Write((uint)ExportedPolicy.FormatVersion);
                writer.Write((uint)shapes.Length);
                for (var layer = 0; layer < shapes.Length; layer++)
                {
                    var rows = shapes[layer][0];
                    var columns = shapes[layer][1];
                    writer.Write((uint)rows);
                    writer.Write((uint)columns);
                    for (var i = 0; i < rows * columns; i++) writer.Write(0f);
                    for (var row = 0; row < rows; row++)
                    {
                        var bias = 0f;
                        if (lastBias != null && layer == shapes.Length - 1 &&
                            row < lastBias.Length)
                            bias = lastBias[row];
                        writer.Write(bias);
                    }
                }
                writer.Flush();
                return stream.ToArray();
            }
        }
    }
}
